[package]
org = "wso2"
name = "EpicFhirR4AdministrationApiService"
version = "0.9.0"
distribution = "2201.7.0"

[[dependency]]
org = "ballerinax"
name = "health.fhir.r4"
version = "4.1.0"

[[dependency]]
org = "ballerinax"
name = "health.fhirr4"
version = "1.0.8"

[[dependency]]
org = "ballerinax"
name = "health.clients.fhir"
version = "1.0.4"
repository="local"

[build-options]
observabilityIncluded = true
